mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls'),name='polls'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns=[		
	#path('',views.index),
	path('',views.employee, name='employee'),
	path('<int:id>/',views.detail,name='detail'),
	path('insert/',views.insert,name='insert'),
]

polls/models.py
from django.db import models

class Employee(models.Model):
	name   = models.CharField(max_length=30)
	age    = models.IntegerField()
	role   = models.CharField(max_length=30)
	salary = models.FloatField()

	def __str__(self):
		return self.name

polls/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
	name=forms.CharField(
		widget=forms.TextInput(attrs={
			'placeholder':'Enter ur name',
			'class':'form-control'}))
	age=forms.IntegerField(
    	widget=forms.NumberInput(attrs={
    		'placeholder':'Enter ur age',
    		'class':'form-control'}))
	role=forms.CharField(
    	widget=forms.TextInput(attrs={
    		'placeholder':'Enter ur role',
    		'class':'form-control'}))
	salary=forms.FloatField(
    	widget=forms.NumberInput(attrs={
    		'placeholder':'Enter ur salary',
    		'class':'form-control'}))

	class Meta:
		model=Employee
		fields='__all__'

polls/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from .models import Employee
from .forms import EmployeeForm
from django.contrib import messages

def index(request):
	return HttpResponse("<marquee><h1>Welcome to My website built in django</h1></marquee>")


def employee(request):
	emp=Employee.objects.all()
	context = {'emp': emp}
	return render(request, 'polls/employee.html', context)


def detail(request,id):
	emp=get_object_or_404(Employee,pk=id)
	return render(request, 'polls/detail.html', {'emp': emp})

def insert(request, uid=1):
    if request.method=='POST':
        inform=EmployeeForm(request.POST)
        if inform.is_valid():
            inform.save()
            messages.info(request,'Information stored Successfully')
            return redirect(insert)
        else:
            messages.info(request,'Invalid data')
            return redirect(insert)    
    else:
        inform=EmployeeForm()
        return render(request,'polls/insert.html',{'inform':inform})

polls/templates/polls/detail.html
<!--<h1>{{emp.id}} => {{ emp.name }}  =>  {{ emp.age }}  =>  {{ emp.role }}  =>  {{ emp.salary }}</h1>-->

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Role</th>
      <th>Salary</th>
    </tr>
   </thead>
   <tbody>
     <tr>
       <td>{{emp.id}}</td>
       <td>{{emp.name}}</td>
       <td>{{emp.age}}</td>
       <td>{{emp.role}}</td>
       <td>{{emp.salary}}</td>
     </tr>
    </tbody>
</table>

polls/templates/polls/employee.html
<!--{% if emp %}
{% load static %}
<ul>
	{% for e in emp %}
		<li><a href="{% url 'polls:detail' e.id %}">{{ e.name }}</a></li>
	{% endfor %}
</ul>

{% else %}
<p>No employee data available</p>

{% endif %}
-->
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Display</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css"  href=" {% static 'polls/css/bootstrap.css' %} " />
    <link rel="stylesheet" type="text/css"  href=" {% static 'polls/css/mdb.css' %} " />
    <link rel="stylesheet" type="text/css"  href=" {% static 'polls/css/fontawesome-all.css' %} " />
    <link rel="stylesheet" type="text/css"  href=" {% static 'polls/css/style.css' %} " />
  
</head>
<body>
<h1 class="text-center text-danger mt-2">Stored Information</h1>
<div class="row">
        <div class="card w-50 mx-auto p-3">
                <div class="card-header bg-light text-center">
                    <h3>Insert ur info</h3>
                </div>
                <div class="card-body">
                    <table class="table table-dark table-responsive-md text-center">
                        <thead class="badge-deep-orange">
                            <tr>

                                <th>ID</th>
							    <th>Name</th>
							    <th>Age</th>
							    <th>Role</th>
							    <th>Salary</th>  
                            </tr>
                        </thead>
                        <tbody>                          
                            {% for i in emp %}
                                 <tr>
                                    <td>{{i.id}}</td>
								    <td>{{i.name}}</td>
								    <td>{{i.age}}</td>
								    <td>{{i.role}}</td>
								    <td>{{i.salary}}</td>
                                 </tr>                                       
                            {% endfor %}
                                
                        </tbody>
                    </table>
                </div>
            </div>
              
</div>  
 
<script src="{% static 'polls/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'polls/js/popper.min.js' %}"></script> 
<script src="{% static 'polls/js/bootstrap.js' %}"></script> 
<script src="{% static 'polls/js/mdb.js' %}"></script> 
<script src="{% static 'polls/js/fontawesome-all.js' %}"></script>     
</body>
</html>

polls/templates/polls/insert.html
    <!DOCTYPE html>
    {% load static %}
    <html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Insert</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css"  href=" {% static 'css/bootstrap.css' %} " />
        <link rel="stylesheet" type="text/css"  href=" {% static 'css/mdb.css' %} " />
        <link rel="stylesheet" type="text/css"  href=" {% static 'css/fontawesome-all.css' %} " />
        <link rel="stylesheet" type="text/css"  href=" {% static 'css/style.css' %} " />
    
    </head>
    <body>
    <h1 class="text-center text-danger mt-2">Please submit Employee information</h1>
    <div class="row">
            <div class="card w-50 mx-auto p-3">
                    <div class="card-header bg-light text-center">
                        <h3>Insert ur info</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="from-group">
                                {% if messages %}
                                    {% for msg in messages %}
                                        <div class="alert alert-{{msg.tags}} alert-dismissible">
                                            <a href="" class="close" data-dissmiss="alert">&times;</a>
                                            {{msg}}
                                        </div>        
                                    {% endfor %}
                                {% endif %}
                                    
                                {{inform.name}}
                                {{inform.age}}
                                {{inform.role}}
                                {{inform.salary}}
                                <input type="submit" value="Submit" class="btn btn-outline-dark-green">
                                <input type="reset" value="Reset" class="btn btn-outline-brown">   
                            </div>
                        </form>
                    </div>
                </div>
                
    </div>  
    
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.js' %}"></script> 
    <script src="{% static 'js/mdb.js' %}"></script> 
    <script src="{% static 'js/fontawesome-all.js' %}"></script>     
    </body>
    </html>